config/routes.rb
Rails.application.routes.draw do
  resources :test_models
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/test_model.rb
class TestModel < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/test_models_controller.rb
class TestModelsController < ApplicationController
  before_action :set_test_model, only: [:show, :edit, :update, :destroy]

  # GET /test_models
  # GET /test_models.json
  def index
    @test_models = TestModel.all
  end

  # GET /test_models/1
  # GET /test_models/1.json
  def show
  end

  # GET /test_models/new
  def new
    @test_model = TestModel.new
  end

  # GET /test_models/1/edit
  def edit
  end

  # POST /test_models
  # POST /test_models.json
  def create
    @test_model = TestModel.new(test_model_params)

    respond_to do |format|
      if @test_model.save
        format.html { redirect_to @test_model, notice: 'Test model was successfully created.' }
        format.json { render :show, status: :created, location: @test_model }
      else
        format.html { render :new }
        format.json { render json: @test_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_models/1
  # PATCH/PUT /test_models/1.json
  def update
    respond_to do |format|
      if @test_model.update(test_model_params)
        format.html { redirect_to @test_model, notice: 'Test model was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_model }
      else
        format.html { render :edit }
        format.json { render json: @test_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_models/1
  # DELETE /test_models/1.json
  def destroy
    @test_model.destroy
    respond_to do |format|
      format.html { redirect_to test_models_url, notice: 'Test model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_model
      @test_model = TestModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_model_params
      params.require(:test_model).permit(:title, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/test_models_helper.rb
module TestModelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTdd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/test_models/_form.html.erb
<%= form_with(model: test_model, local: true) do |form| %>
  <% if test_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(test_model.errors.count, "error") %> prohibited this test_model from being saved:</h2>

      <ul>
        <% test_model.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/test_models/edit.html.erb
<h1>Editing Test Model</h1>

<%= render 'form', test_model: @test_model %>

<%= link_to 'Show', @test_model %> |
<%= link_to 'Back', test_models_path %>

app/views/test_models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Test Models</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_models.each do |test_model| %>
      <tr>
        <td><%= test_model.title %></td>
        <td><%= test_model.text %></td>
        <td><%= link_to 'Show', test_model %></td>
        <td><%= link_to 'Edit', edit_test_model_path(test_model) %></td>
        <td><%= link_to 'Destroy', test_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test Model', new_test_model_path %>

app/views/test_models/new.html.erb
<h1>New Test Model</h1>

<%= render 'form', test_model: @test_model %>

<%= link_to 'Back', test_models_path %>

app/views/test_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @test_model.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @test_model.text %>
</p>

<%= link_to 'Edit', edit_test_model_path(@test_model) %> |
<%= link_to 'Back', test_models_path %>